### ISSUE TITLE
Less restrictive `new GhostAdminApi()` arguments

### ISSUE THREAD

**Issue by kevinansfield** [TryGhost/Ghost-SDK#46]
I wonder if it's necessary to have the strict requirements of a `host` with no trailing slash and a `ghostPath` with no leading/trailing slash when creating a new GhostAdminAPI instance?

In Zapier we've always asked the user for their "Admin URL" as it's easy to explain and they only need to copy/paste the URL after loading their admin screen (they should know where this is 😄). However, that results in some ugly code to work around the strict initialiser argument requirements:

```javascript
const {URL} = require('url');
const GhostAdminApi = require('@tryghost/admin-api');

// Convenience method for creating a GhostAdminAPI instance from the bundle data
const initAdminApi = ({adminUrl, adminApiKey: key}) => {
    // we get the "Admin URL" from the user as it's less error prone and easier
    // to explain but GhostAdminAPI requires a specific host/path combination
    const url = new URL(adminUrl);
    const host = url.origin.replace(/\/$/, '');
    const ghostPath = url.pathname.replace(/^\/|\/$/g, '');

    return new GhostAdminApi({
        host,
        ghostPath,
        key,
        version: 'v2'
    });
};
```

Perhaps we can make the initialiser more forgiving so that we only need to pass in a URL?

**Comment by ErisDS** [comment]
We don't currently do this for the content API, leaning towards throwing errors until the correct URL is provided.

The reasoning behind this, is that people interacting with our SDK tools are developers, and developers have a better experience when they understand what's happening beneath them. E.g. tell them to enter https, don't magically change http to https without them knowing.

Zapier is a very interesting client example, because in this case, Kevin is the developer of a shared client, and people interacting with the shared client (Zapier) are users. Users have significantly less tolerance for errors as well as less interest in what's happening under the hood, so for users, magic is more desirable.

This is _always_ a fine balance to tread.

In this case, I _think_ at least right now, that it makes sense that Kevin as the developer of a client for non developer users has to handle some extra logic, but:

- Are we able to validate the URL in Zapier at all? E.g. to ensure we're handed HTTPS. 
- `ghostPath` is currently not editable, so I don't think you have to account for that right now. 

The slash / no slash is the one thing where maybe we should handle it in the admin-api tool, cos it's something most people don't notice. It's an implementation detail of Ghost, not an important distinction like the fact that admin URLs _must_ be https.

**Comment by kevinansfield** [comment]
> Users have significantly less tolerance for errors as well as less interest in what's happening under the hood, so for users, magic is more desirable.

👍 agreed. Good point on the desired audience for each tool.

> * Are we able to validate the URL in Zapier at all? E.g. to ensure we're handed HTTPS.

Yes, that's doable 👍 

> * `ghostPath` is currently not editable, so I don't think you have to account for that right now.

With the current SDK design I found that ambiguous. There are arguments for `host` and the `ghostPath` - in the case of a sub-directory install which argument should the subdirectory path element be added to? The strict leading/trailing slash complicates this because if you have a sub-directory install I think it's common to say your "host" would be https://mysite.com/blog/ rather than https://mysite.com/blog (I was actually tripped up by this and took the `ghostPath` to be the full path to ghost incl. the subdir rather than appending the non-trailing-slash subdir onto the `host`

**Comment by ErisDS** [comment]
> With the current SDK design I found that ambiguous. There are arguments for `host` and `ghostPath` - in the case of a sub-directory install which argument should the subdirectory path element be added to?

Good questions.

`ghostPath` is a stopgap solution for us having hardcoded `/ghost/` in the SDK, so that in future when this does become customisable, it's an extra config option already. It's not documented in the Content SDK: https://docs.ghost.org/api/javascript/.

`host` should be your admin URL including any subdirectory, although perhaps `host` wasn't the best name 🤔

This does me back to my previous suggestion about having host listed on the integration screen, to make it absolutely clear what to paste into this field cc @peterzimon

**Comment by kevinansfield** [comment]
> This does me back to my previous suggestion about having host listed on the integration screen, to make it absolutely clear what to paste into this field cc @peterzimon

If we do this then we can update the Zapier auth screen too so it has an "API Host" field rather than "Admin URL", seems like that will be more future-proof too.

**Comment by kevinansfield** [comment]
I think if we expose an "Content/Admin API URL" in the in the integrations screen we can also simplify the SDK arguments so that only a URL is passed in.

`new GhostAdminAPI({adminApiUrl: 'https://mysite.com/ghost/api/', version: 'v2'})`. I don't see why the `ghostPath` argument is necessary, it seems like it's an internal implementation detail that even developers shouldn't need to care about, if it's only about validation then we can do that just as easily with a URL without needing to make the arguments more confusing.

If a URL can be provided then it's also future-proof as it allows for any part of the URL to be changed if it's configurable later on, eg. in  I have my API configured to live at https://api.mysite.com/ 🤔 but my "admin" SPA lives on https://admin.mysite.com.

**Comment by peterzimon** [comment]
@kevinansfield 
Here's how we should change the custom integration screen in Ghost Admin.

<img width="1126" alt="custom-integrations-update" src="https://user-images.githubusercontent.com/353959/52480021-d2a56480-2baa-11e9-967c-6fdc62123848.png">

**Notes:**
- "Copy" button appears only on row hover (similarly to current version)
- "Copied to clipboard" should flash temporarily instead of the key/URL value in the given row
- we can reuse the same design for the Zapier integration screen and extend it with a little help to bring attention that these values will be needed on Zapier connect

**Comment by ErisDS** [comment]
Should we maybe add url to both the content and admin sdk, and deprecate `host` - remove it from docs, have it work for now, remove it whenever we have a good moment?

**Comment by kirrg001** [comment]
@kevinansfield What is the state of this issue? Is it done?

**Comment by kevinansfield** [comment]
The UI side of things in Ghost-Admin is done. @ErisDS's suggestion for swapping `host` (with deprecation) for `url` sounds good, I'll confirm and implement.
