### ISSUE TITLE
React App: Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by rsarai** [TryGhost/Ghost-SDK#72]
### Issue Summary
I'm trying to use the `@tryghost/admin-api` on a React and webpack application. I'm having the following error:
```
ERROR in ./node_modules/@tryghost/admin-api/lib/index.js
    Module not found: Error: Can't resolve 'fs' in
```
I'm aware that react doesn't allow me to have the fs module as pointed out in this answer: https://stackoverflow.com/a/48359480/7537918. However I wanna know if there's any work around on this.

### To Reproduce

1. npm i @tryghost/admin-api
2. import GhostAdminAPI from '@tryghost/admin-api'

### Technical details:

* Ghost Version: 2.18
* Node Version: 10.13.0
* Browser/OS: any
* Database: any

**Comment by kevinansfield** [comment]
The admin-api package is only supposed to be used from server-side (node.js) code because admin api keys should never be shared in the way that would be necessary for client-side code to work.

What is your use-case? Maybe there’s a different approach than trying to bundle server-side libraries into your client code.

**Comment by rsarai** [comment]
Oh :scream_cat: I see. 

I'm using ghost as my backend and have a separated frontend. I'm trying to build a preview feature on my side, I realized that the `content-api` doesn't return me any posts with the `draft` status. I was trying to get those post through the `admin-api`, which I should not be doing as you said. Do you see a solution for this?

Thanks again @kevinansfield for the prompt response!

**Comment by ErisDS** [comment]
@rsarai Previews are currently considered private data, rather than public and are only available via the admin API, which cannot be used client-side. We are aware of the difficulties this causes and are still working on a plan for the best way to solve this long term. 

In the meantime, the correct approach would be to run a small server-side "proxy" service that speaks to the admin API and will return preview data for you. You can authenticate with your service however you choose, meaning the level of privacy & security afforded to the data is fully within your control. 

Totally get that this isn't ideal, but it is at least possible 🙂

**Comment by rsarai** [comment]
@ErisDS Thank you! I will totally check this option

**Comment by ErisDS** [comment]
Great, I'm going to close this issue now as the original report isn't a bug, and we've identified a workaround for what you want to achieve.

**Comment by webdeb** [comment]
Why is this closed? should't we add "fs" to the dependencies to make the cli not throwing errors?

**Comment by webdeb** [comment]
@underthehoodlearning A proxy service is just a server like express which forwards your requests to another service (in this case ghost). This might sound complex when you haven't had any experience with it. Play with `express` or something like this.

**Comment by underthehoodlearning** [comment]
@webdeb: I got it. I was able to set up the NodeJS app using express. Thanks!
